"""Add age to Chat model

Revision ID: 25fbfb7eabb5
Revises: 6d9d2876063b
Create Date: 2025-05-16 08:00:24.595419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fbfb7eabb5'
down_revision = '6d9d2876063b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
